export default {
  EXAMPLES_HEIGHT: 8,
  EXAMPLES_PADDING: 10,
  EXAMPLES_RADIUS: 7,
  DEFAULT_FOG_COLOR: '#ADD8E6',
  DEFAULT_LIGHT_COLOR: '#FFFFFF',
  DEFAULT_LIGHT_INTENSITY: 1,
  SPEED_ROTATION: 0.01,
};
